directory: ~/Dropbox/Music
import:
    move: yes

paths:
    default: %asciify{$artist - $title}
    singleton: %asciify{$artist - $title}
    comp: %asciify{$artist - $title}

ui:
    color: yes

plugins: fetchart embedart lastgenre mbsync

fetchart:
    auto: no
