# i3status configuration file.

general {
    colors = true
    interval = 1
    # output_format = "i3bar"
}

order += "cpu_usage"
order += "load"
order += "time"
order += "tztime mtv"

cpu_usage {
    format = " CPU: %usage"
}

load {
    format = " load: %1min %5min %15min"
}

time {
    format = " %d %b %H:%M"
}

tztime mtv {
    format = "[%H:%M %Z]"
    timezone = "PST8PDT"
}
