#!/bin/bash
[ -r /etc/bashrc.local ] && source /etc/bashrc.local

# local helpers
alias gvim='/Applications/MacVim.app/Contents/MacOS/Vim -g'

# remote helpers
gssh() {
    if ! kinit -R 2> /dev/null ; then
        kinit
    fi
    ssh $@
}

alias g='gssh janus -t'

gtmux() {
    SESSION=${1:-`hostname -s`}
    g "tmx -CC $SESSION"
}
