#!/usr/sbin/nft -f

flush ruleset

table inet filter {
	chain input {
		type filter hook input priority 0; policy accept;

                # Accept safe connections
		iifname "lo" accept
		ct state established,related counter accept

                # SYN flood protection
		tcp flags & (fin | syn | rst | ack) == syn counter jump syn-flood
		ip protocol icmp counter jump icmp-flood
	}

	chain syn-flood {
		limit rate 50/second burst 100 packets counter return
		counter log prefix "SYN flood: "
		counter drop
	}

	chain icmp-flood {
		limit rate 5/second burst 10 packets counter return
		counter log prefix "ICMP flood: "
		counter drop
	}
}
