#! /usr/bin/env bash

PS1='\[\033[01;31m\]\h\[\033[01;34m\] \W \$\[\033[00m\] \[\e]0;\a\007\]'

# Environment variables
export LANG="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

export EDITOR="vim"
export PAGER="less -R"
export HISTSIZE=10000
export HH_CONFIG=hicolor,rawhistory

# Aliases
alias ls='ls -G'
alias grep='grep --colour=auto'

alias la='ls -A'
alias ll='ls -l'
alias l='ls -lA'
